name: Nestjs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test

  test:
    needs: lint # 앞에 lint가 성공해야만 test가 돌아가게 만드는 needs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
  deploy:
    needs: test # test가 선행적으로 성공해야만 deploy가 실행된다.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with: # Repository secrets 에서 준 키들이 여기서 환경변수로 설정된다.
          host: ${{ secrets.HOST }} // ip주소
          username: ${{ secrets.USERNAME }} // ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/Tickets_project
            
            # GitHub에서 최신 코드를 가져옴
            git pull
            
            # .env 파일 생성
            echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
            echo "DB_SYNC=${{ secrets.DB_SYNC }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

						# node 관련 환경 설정 가져오기 위해 실행
            source /home/ubuntu/.nvm/nvm.sh
            # 서버 실행 시크립트 가동!
            source ./run.sh